import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Navbar2 from '@/components/Navbar2'
import SubNavbar from '@/components/Home/SubNavbar'
import Providers from './Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className} >
      <Providers>

        {/* <Navbar></Navbar> */}
        <SubNavbar></SubNavbar>
        <Navbar2></Navbar2>
          {children}
        <Footer></Footer>
        </Providers>

      </body>
    </html>
  )
}
